--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimplePets
build-by-default: true
branches:
- master
projects:
  SimplePets:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: 3.4.0
      - src: SOF3/await-generator/await-generator
        version: 3.1.0
...
