--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimplePets
build-by-default: true
branches:
  - master
  - pm3

projects:
  SimplePets:
    icon: "/assets/logo-min.png"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.3.1
      - src: muqsit/InvMenu/InvMenu
        version: ^4.1.1
    lint:
      phpstan: false
...
