name: SimplePets
main: brokiem\simplepets\SimplePets
version: 0.0.1-snapshot
api: 4.0.0
authors: [ "broki", "brokiem", "broski" ]

website: https://github.com/brokiem/SimplePets

extensions:
  Core: '>=8.0'

permissions:
  simplepets.spawn:
    default: op
  simplepets.remove:
    default: op
  simplepets.inv:
    default: true