api: 4.0.0
main: brokiem\simplepets\SimplePets
name: SimplePets
version: 0.0.1-snapshot
authors: [ "broki", "brokiem", "broski" ]
website: https://github.com/brokiem/SimplePets
extensions:
  Core: '>=8.0'

permissions:
  simplepets.spawn:
    default: op
  simplepets.remove:
    default: op